data:
    type: "LLdataset"
    train_dataset: "low-light"
    val_dataset: "low-light"
    patch_size: 256
    channels: 3
    num_workers: 4
    data_dir: "./data/"
    ckpt_dir: "ckpt2/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 8
    n_epochs: 40
    validation_freq: 1000
    model_variant: "ddpm2"
    photo_mse_weight: 1.0
    photo_ssim_weight: 0.5
    lpips_weight: 0.05
    loss_log_name: "loss_log_ddm2.csv"
    latest_ckpt_name: "latest"
    best_ckpt_name: "bestbest"

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
